name: Terraform CI/CD

on:
    push:
        branches:
            - main
            pull_request:
jobs:
    terraform:
        name: 'Terraform Validate and Plan'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
            uses: actions/checkout@v3
